"""Offline discovery-index regressions; no EEGDash import or recordings needed."""

import importlib.util
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location(
    "llms_generator", ROOT / "docs/generate_llms_txt.py"
)
llms = importlib.util.module_from_spec(spec)
spec.loader.exec_module(llms)


def page(source, name, content):
    path = source / "api/dataset" / f"eegdash.dataset.{name}.rst"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return path


def test_classify_by_dataset_directive_not_filename(tmp_path):
    for name in ("DS001234", "nm000001", "OtherArchive_42"):
        page(tmp_path, name, f".. dataset-page:: {name}\n")
    for name in ("base", "dataset", "registry"):
        page(tmp_path, name, f".. automodule:: eegdash.dataset.{name}\n")
    page(tmp_path, "DSwrong", ".. dataset-page:: DSother\n")
    assert [name for name, _ in llms._discover_dataset_pages(tmp_path)] == [
        "DS001234",
        "OtherArchive_42",
        "nm000001",
    ]
    assert {name for name, _ in llms._discover_api_pages(tmp_path)} >= {
        "eegdash.dataset.base",
        "eegdash.dataset.dataset",
        "eegdash.dataset.registry",
    }


def test_custom_url_and_determinism(tmp_path):
    page(tmp_path, "base", ".. automodule:: eegdash.dataset.base\n")
    page(tmp_path, "nm000001", ".. dataset-page:: nm000001\n")
    output = tmp_path / "llms.txt"
    llms.build(tmp_path, output, "https://preview.example/v2/")
    first = output.read_bytes()
    assert b"https://eegdash.org" not in first
    assert b"https://preview.example/v2/api/dataset/eegdash.dataset.base.html" in first
    llms.build(tmp_path, output, "https://preview.example/v2/")
    assert output.read_bytes() == first


def test_budget_counts_only_listed_entries_and_signals_truncation(tmp_path):
    for i in range(1000):
        name = f"Archive_é_{i:04}"
        page(tmp_path, name, f".. dataset-page:: {name}\n")
    output = tmp_path / "llms.txt"
    size = llms.build(tmp_path, output)
    text = output.read_text()
    dataset_section = text.split("## Dataset pages", 1)[1]
    listed = len(re.findall(r"^- \[", dataset_section, re.M))
    assert 0 < listed < 1000
    assert f"(N={listed})" in dataset_section
    assert f"Showing {listed} of 1000" in dataset_section
    assert "truncated" in dataset_section.lower()
    assert size <= llms.SIZE_BUDGET


def test_missing_generated_directory_is_explicit(tmp_path):
    output = tmp_path / "llms.txt"
    llms.build(tmp_path / "missing", output)
    assert "Dataset pages (N=0)" in output.read_text()
    assert "No generated dataset pages" in output.read_text()


def test_curated_html_links_have_current_sources():
    links = re.findall(r"\{site\}/([^)>]+\.html)", llms.CURATED_HEADER)
    missing = []
    for link in links:
        relative = Path(link).with_suffix(".rst")
        if link.startswith("generated/auto_examples/"):
            example = link.removeprefix("generated/auto_examples/")
            if example == "index.html":
                continue
            exists = (ROOT / "examples" / Path(example).with_suffix(".py")).is_file()
        elif link == "api/dataset/eegdash.EEGDashDataset.html":
            continue  # generated by dataset_page.shells
        else:
            exists = (ROOT / "docs/source" / relative).is_file()
        if not exists:
            missing.append(link)
    assert missing == []


def test_sphinx_build_generates_index_after_shells_and_checks_links(tmp_path):
    source = tmp_path / "source"
    source.mkdir()
    (source / "conf.py").write_text(
        f"import sys\nsys.path.insert(0, {str(ROOT / 'docs')!r})\n"
        "extensions = ['generate_llms_txt']\n"
        "html_baseurl = 'https://preview.example/v2/'\n"
        "def shells(app):\n"
        "    from pathlib import Path\n"
        "    p = Path(app.srcdir) / 'api/dataset/eegdash.dataset.nm000001.rst'\n"
        "    p.parent.mkdir(parents=True, exist_ok=True)\n"
        "    p.write_text('Dataset\\n=======\\n\\n.. dataset-page:: nm000001\\n')\n"
        "def setup(app):\n"
        "    from docutils.parsers.rst import Directive\n"
        "    class Dataset(Directive):\n"
        "        required_arguments = 1\n"
        "        def run(self): return []\n"
        "    app.add_directive('dataset-page', Dataset)\n"
        "    app.connect('builder-inited', shells)\n"
    )
    # Minimal stand-ins for all curated HTML/assets, not real data or network.
    for link in re.findall(r"\{site\}/([^)>]+)", llms.CURATED_HEADER):
        if link.endswith(".html"):
            path = source / Path(link).with_suffix(".rst")
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text("Page\n====\n")
        else:
            path = source / "_extra" / link
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text("fixture")
    with (source / "conf.py").open("a") as f:
        f.write("html_extra_path = ['_extra']\n")
    output = tmp_path / "html"
    result = subprocess.run(
        [sys.executable, "-m", "sphinx", "-b", "html", str(source), str(output)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    text = (output / "llms.txt").read_text()
    assert "Dataset pages (N=1)" in text
    assert (
        "https://preview.example/v2/api/dataset/eegdash.dataset.nm000001.html" in text
    )
    llms.validate_links(output / "llms.txt", output, "https://preview.example/v2/")
    (output / "install/install_pip.html").unlink()
    with pytest.raises(ValueError, match="install/install_pip.html"):
        llms.validate_links(output / "llms.txt", output, "https://preview.example/v2/")
