"""Croissant 1.0 descriptor validity gate.

EEGDash distributes a machine-readable Croissant (MLCommons JSON-LD)
descriptor per dataset, generated by ``_build_croissant_export`` in
``docs/source/conf.py`` and written alongside each dataset's docs page.
The paper claims Croissant 1.0 / MLCommons distribution; a referee can run
the MLCommons validator against an emitted descriptor.

This module is that gate. It:

1. builds a descriptor from a representative dataset context, then
2. asserts the Croissant 1.0 structural invariants (``conformsTo``,
   ``@type``, ``@context``, distributions) that hold without any extra
   dependency, and
3. validates the descriptor with the official ``mlcroissant`` library when
   it is installed (the real MLCommons gate). When ``mlcroissant`` is not
   installed the validation step skips with a clear message rather than
   failing — install ``mlcroissant`` (it is listed as a docs/validation
   optional dependency) to enforce the gate in CI.

The descriptor builder lives in the Sphinx ``conf.py``, which imports
``sphinx``. When the docs stack is not installed the whole module skips.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

# Locate docs/source/conf.py relative to the repo root (tests/unit_tests/..).
_REPO_ROOT = Path(__file__).resolve().parents[2]
_CONF_PY = _REPO_ROOT / "docs" / "source" / "conf.py"


def _load_docs_conf():
    """Import docs/source/conf.py as a module, or skip if it cannot load.

    ``conf.py`` imports ``sphinx`` and a few docs-only extensions; when the
    ``docs`` optional dependencies are not installed the import fails and the
    Croissant gate is not applicable in this environment.
    """
    if not _CONF_PY.exists():
        pytest.skip(f"docs conf.py not found at {_CONF_PY}")
    spec = importlib.util.spec_from_file_location("eegdash_docs_conf", _CONF_PY)
    if spec is None or spec.loader is None:
        pytest.skip("could not build import spec for docs conf.py")
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except Exception as exc:  # pragma: no cover - environment dependent
        pytest.skip(f"docs conf.py not importable (docs deps missing?): {exc}")
    if not hasattr(module, "_build_croissant_export"):
        pytest.skip("docs conf.py does not expose _build_croissant_export")
    return module


# A representative dataset context, mirroring the fields conf.py threads into
# the export at docs-build time. Kept self-contained so the gate needs no
# network and no live dataset.
_SAMPLE_CONTEXT = {
    "class_name": "DS002718",
    "dataset_id": "ds002718",
    "title": "Multisubject, multimodal face processing",
    "modality": "EEG",
    "doi": "10.18112/openneuro.ds002718.v1.0.5",
    "license": "CC0",
    "authors": ["Wakeman, D.", "Henson, R."],
    "datatypes": ["eeg"],
    "tags": {"modality": "Visual", "type": "Perception", "pathology": "Healthy"},
    "openneuro_url": "https://openneuro.org/datasets/ds002718",
    "tasks": ["FaceRecognition"],
    "bids_version": "1.8.0",
    "dataset_storage": {"base": "s3://openneuro.org/ds002718"},
    "year": "2019",
}

# A minimal context (only the fields conf.py treats as load-bearing) to make
# sure the builder degrades gracefully for sparse metadata.
_MINIMAL_CONTEXT = {
    "class_name": "DS000001",
    "dataset_id": "ds000001",
}


def _build(context):
    conf = _load_docs_conf()
    return conf._build_croissant_export(context)


@pytest.mark.parametrize(
    "context", [_SAMPLE_CONTEXT, _MINIMAL_CONTEXT], ids=["rich", "minimal"]
)
def test_descriptor_has_croissant_1_0_invariants(context):
    """Every emitted descriptor declares Croissant 1.0 + schema.org Dataset."""
    doc = _build(context)

    assert doc.get("conformsTo") == "http://mlcommons.org/croissant/1.0", (
        "descriptor must declare Croissant 1.0 conformance"
    )
    assert doc.get("@type") == "sc:Dataset"
    assert isinstance(doc.get("@context"), dict)
    # The Croissant context must define the `cr:` namespace prefix.
    assert doc["@context"].get("cr") == "http://mlcommons.org/croissant/"
    # Dataset must be named.
    assert isinstance(doc.get("name"), str) and doc["name"].strip()


def test_descriptor_distributions_are_well_formed():
    """Distribution entries are FileObjects with id, name, and contentUrl."""
    doc = _build(_SAMPLE_CONTEXT)
    distributions = doc.get("distribution")
    assert isinstance(distributions, list) and distributions, (
        "rich context should yield at least one distribution"
    )
    for dist in distributions:
        assert dist.get("@type") == "cr:FileObject"
        assert dist.get("@id")
        assert dist.get("name")
        assert dist.get("contentUrl")
        assert dist.get("encodingFormat")
        # Croissant 1.0 requires a content hash on every FileObject; the
        # emitter sets one (a sentinel for live/versioned resources). Without
        # it the official mlcroissant validator rejects the descriptor.
        assert dist.get("sha256") or dist.get("md5"), (
            f"FileObject {dist.get('@id')!r} is missing a required content hash"
        )


def test_descriptor_is_json_serializable():
    """The descriptor must serialize to JSON (it is written to disk as such)."""
    doc = _build(_SAMPLE_CONTEXT)
    payload = json.dumps(doc)
    assert json.loads(payload)["conformsTo"] == "http://mlcommons.org/croissant/1.0"


def test_descriptor_validates_with_mlcroissant():
    """Official MLCommons gate: load the descriptor with ``mlcroissant``.

    Skips (with a clear message) when ``mlcroissant`` is not installed so the
    suite stays green in minimal environments; install ``mlcroissant`` to
    enforce the gate. ``mlcroissant.Dataset(jsonld=...)`` runs the library's
    JSON-LD parsing and conformance checks and raises on a malformed
    descriptor.
    """
    mlc = pytest.importorskip(
        "mlcroissant",
        reason=(
            "mlcroissant not installed; install it (e.g. `pip install "
            "mlcroissant`) to enforce the Croissant 1.0 validity gate."
        ),
    )

    doc = _build(_SAMPLE_CONTEXT)
    # Constructing a Dataset triggers mlcroissant's validation of the JSON-LD.
    dataset = mlc.Dataset(jsonld=doc)
    assert dataset.metadata is not None
    assert dataset.metadata.name
