r"""Feature Extraction Module.

This module provides tools for feature extraction from :mode:`braindecode`
datasets, as well as a bank of predefined features.

"""

from .base_utils import BivariateIterator
from .datasets import FeaturesConcatDataset, FeaturesDataset
from .decorators import (
    FeatureKind,
    FeaturePredecessor,
    PreprocessorOutputType,
    bivariate_feature,
    metadata_preprocessor,
    multivariate_feature,
    univariate_feature,
)
from .extractors import FeatureExtractor
from .feature_bank import (  # Complexity; Connectivity; CSP; Dimensionality; Signal; Spectral
    CommonSpatialPattern,
    SignalOutputType,
    complexity_approx_entropy,
    complexity_entropy_preprocessor,
    complexity_lempel_ziv,
    complexity_multiscale_entropy,
    complexity_sample_entropy,
    complexity_svd_entropy,
    connectivity_coherency_preprocessor,
    connectivity_imaginary_coherence,
    connectivity_lagged_coherence,
    connectivity_magnitude_square_coherence,
    dimensionality_detrended_fluctuation_analysis,
    dimensionality_higuchi_fractal_dim,
    dimensionality_hurst_exp,
    dimensionality_katz_fractal_dim,
    dimensionality_petrosian_fractal_dim,
    pick_channel_pairs_preprocessor,
    pick_channels_preprocessor,
    signal_decorrelation_time,
    signal_filter_preprocessor,
    signal_hilbert_preprocessor,
    signal_hjorth_activity,
    signal_hjorth_complexity,
    signal_hjorth_mobility,
    signal_kurtosis,
    signal_line_length,
    signal_mean,
    signal_peak_to_peak,
    signal_quantile,
    signal_root_mean_square,
    signal_skewness,
    signal_std,
    signal_variance,
    signal_zero_crossings,
    spectral_bands_power,
    spectral_db_preprocessor,
    spectral_edge,
    spectral_entropy,
    spectral_hjorth_activity,
    spectral_hjorth_complexity,
    spectral_hjorth_mobility,
    spectral_moment,
    spectral_normalized_preprocessor,
    spectral_preprocessor,
    spectral_root_total_power,
    spectral_slope,
)
from .inspect import (
    get_all_feature_kinds,
    get_all_feature_preprocessors,
    get_all_features,
    get_all_preprocessor_output_types,
    get_feature_kind,
    get_feature_predecessors,
)
from .kinds import (
    BivariateFeature,
    MultivariateFeature,
    UnivariateFeature,
)
from .output_types import (
    AsInputOutputType,
    BasePreprocessorOutputType,
)
from .serialization import (
    feature_extractor_from_dict,
    load_feature_extractor_from_hocon,
    load_feature_extractor_from_json,
    load_feature_extractor_from_yaml,
    load_features_concat_dataset,
)
from .trainable import TrainableFeature
from .utils import extract_features, fit_feature_extractors

__all__ = [
    "BivariateIterator",
    "FeaturesConcatDataset",
    "FeaturesDataset",
    "FeatureKind",
    "FeaturePredecessor",
    "PreprocessorOutputType",
    "bivariate_feature",
    "metadata_preprocessor",
    "multivariate_feature",
    "univariate_feature",
    "FeatureExtractor",
    "get_all_feature_preprocessors",
    "get_all_feature_kinds",
    "get_all_features",
    "get_all_preprocessor_output_types",
    "get_feature_kind",
    "get_feature_predecessors",
    "BivariateFeature",
    "MultivariateFeature",
    "UnivariateFeature",
    "AsInputOutputType",
    "BasePreprocessorOutputType",
    "feature_extractor_from_dict",
    "load_feature_extractor_from_hocon",
    "load_feature_extractor_from_json",
    "load_feature_extractor_from_yaml",
    "load_features_concat_dataset",
    "TrainableFeature",
    "extract_features",
    "fit_feature_extractors",
    # Feature part
    # Complexity
    "complexity_entropy_preprocessor",
    "complexity_approx_entropy",
    "complexity_multiscale_entropy",
    "complexity_sample_entropy",
    "complexity_svd_entropy",
    "complexity_lempel_ziv",
    # Connectivity
    "connectivity_coherency_preprocessor",
    "connectivity_magnitude_square_coherence",
    "connectivity_imaginary_coherence",
    "connectivity_lagged_coherence",
    # CSP
    "CommonSpatialPattern",
    # Dimensionality
    "dimensionality_higuchi_fractal_dim",
    "dimensionality_petrosian_fractal_dim",
    "dimensionality_katz_fractal_dim",
    "dimensionality_hurst_exp",
    "dimensionality_detrended_fluctuation_analysis",
    # Pick
    "pick_channel_pairs_preprocessor",
    "pick_channels_preprocessor",
    # Signal
    "SignalOutputType",
    "signal_filter_preprocessor",
    "signal_hilbert_preprocessor",
    "signal_mean",
    "signal_variance",
    "signal_skewness",
    "signal_kurtosis",
    "signal_std",
    "signal_root_mean_square",
    "signal_peak_to_peak",
    "signal_quantile",
    "signal_zero_crossings",
    "signal_line_length",
    "signal_hjorth_activity",
    "signal_hjorth_mobility",
    "signal_hjorth_complexity",
    "signal_decorrelation_time",
    # Spectral
    "spectral_preprocessor",
    "spectral_normalized_preprocessor",
    "spectral_db_preprocessor",
    "spectral_root_total_power",
    "spectral_moment",
    "spectral_entropy",
    "spectral_edge",
    "spectral_slope",
    "spectral_bands_power",
    "spectral_hjorth_activity",
    "spectral_hjorth_mobility",
    "spectral_hjorth_complexity",
]
