r"""Serialization Utilities for Feature Datasets.

This module provides functions for reconstructing feature datasets
from disk. It serves as the inverse of the saving logic implemented in
:class:`FeaturesConcatDataset`, allowing for efficient, parallelized
reloading of processed features and their associated metadata.

See Also
--------
https://github.com/braindecode/braindecode/blob/master/braindecode/datautil/serialization.py#L165-L229

"""

from __future__ import annotations

from functools import partial
from pathlib import Path

import pandas as pd
from joblib import Parallel, delayed
from mne.io import read_info

from braindecode.datautil.serialization import _load_kwargs_json

from .datasets import FeaturesConcatDataset, FeaturesDataset
from .extractors import FeatureExtractor

__all__ = [
    "load_features_concat_dataset",
]


def load_features_concat_dataset(
    path: str | Path, ids_to_load: list[int] | None = None, n_jobs: int = 1
) -> FeaturesConcatDataset:
    r"""Load a stored :class:`FeaturesConcatDataset` from a directory.

    This function reconstructs a concatenated dataset by loading individual
    :class:`FeaturesDataset` instances from numbered subdirectories.

    Parameters
    ----------
    path : str or pathlib.Path
        The root directory where the dataset was previously saved. This
        directory should contain numbered subdirectories.
    ids_to_load : list of int, optional
        A list of specific recording IDs (subdirectory names) to load.
        If **None**, all numbered subdirectories found in the path are
        loaded in ascending numerical order.
    n_jobs : int, default=1
        The number of CPU cores to use for parallel loading. Set to -1 to
        use all available processors.

    Returns
    -------
    FeaturesConcatDataset
        A unified concatenated dataset containing the loaded recordings.

    Notes
    -----
    The function expects the directory structure generated by
    :meth:`FeaturesConcatDataset.save`. It automatically reconstructs
    the feature DataFrames (Parquet), metadata (Pickle), recording info
    (FIF), and preprocessing keyword arguments (JSON).

    """
    # Verify work with a pathlib.Path
    path = Path(path)

    if ids_to_load is None:
        # Get all subdirectories and sort them numerically
        ids_to_load = [p.name for p in path.iterdir() if p.is_dir()]
        ids_to_load = sorted(ids_to_load, key=lambda i: int(i))
    ids_to_load = [str(i) for i in ids_to_load]

    datasets = Parallel(n_jobs)(delayed(_load_parallel)(path, i) for i in ids_to_load)
    return FeaturesConcatDataset(datasets)


def _load_parallel(path: Path, i: str) -> FeaturesDataset:
    r"""Load a single :class:`FeaturesDataset` from its subdirectory.

    Internal helper function for :func:`load_features_concat_dataset`.

    Parameters
    ----------
    path : pathlib.Path
        The root path of the saved concatenated collection.
    i : str
        The identifier of the dataset (directory name) to load.

    Returns
    -------
    FeaturesDataset
        The reconstructed recording-level dataset instance.

    Notes
    -----
    This helper looks for files following the standard naming convention:
    - ``{i}-feat.parquet``: Feature values.
    - ``metadata_df.pkl``: Sample-level metadata.
    - ``description.json``: Dataset-level description.
    - ``raw-info.fif``: Original recording info (if available).

    """
    sub_dir = path / i

    parquet_name_pattern = "{}-feat.parquet"
    parquet_file_name = parquet_name_pattern.format(i)
    parquet_file_path = sub_dir / parquet_file_name

    features = pd.read_parquet(parquet_file_path)

    description_file_path = sub_dir / "description.json"
    description = pd.read_json(description_file_path, typ="series")

    raw_info_file_path = sub_dir / "raw-info.fif"
    raw_info = None
    if raw_info_file_path.exists():
        raw_info = read_info(raw_info_file_path)

    raw_preproc_kwargs = _load_kwargs_json("raw_preproc_kwargs", sub_dir)
    window_kwargs = _load_kwargs_json("window_kwargs", sub_dir)
    window_preproc_kwargs = _load_kwargs_json("window_preproc_kwargs", sub_dir)
    features_kwargs = _load_kwargs_json("features_kwargs", sub_dir)
    metadata = pd.read_pickle(path / i / "metadata_df.pkl")

    dataset = FeaturesDataset(
        features,
        metadata=metadata,
        description=description,
        raw_info=raw_info,
        raw_preproc_kwargs=raw_preproc_kwargs,
        window_kwargs=window_kwargs,
        window_preproc_kwargs=window_preproc_kwargs,
        features_kwargs=features_kwargs,
    )
    return dataset


def _func_from_dict(func_dict):
    """Get a feature_bank function from a dictionary.

    Parameters
    ----------
    func_dict : dict
        A dictionary representing the function, containing its name, as well
        as its arguments and keyword arguments (for partial functions).

    Returns
    -------
    Callable | functools.Partial
        A function

    See Also
    --------
    ~eegdash.features.extractors._func_to_dict

    """
    from . import feature_bank

    if func_dict["name"] in feature_bank.__all__:
        func = getattr(feature_bank, func_dict["name"])
    else:
        raise ValueError(
            f"feature or preprocessor named `{func_dict['name']}` "
            + "not found in feature bank."
        )
    if "args" in func_dict or "kwargs" in func_dict:
        func_args = func_dict["args"] if "args" in func_dict else []
        func_kwargs = func_dict["kwargs"] if "kwargs" in func_dict else {}
        func = partial(func, *func_args, **func_kwargs)
    return func


def feature_extractor_from_dict(fe_dict):
    """Get a feature extractor from a dictionary.

    Parameters
    ----------
    fe_dict : dict
        A dictionary representing the feature extractor, with
        "feature_extractors" and "preprocessor" fields (if applicable).

    Returns
    -------
    FeatureExtractor
        A feature extractor

    See Also
    --------
    ~eegdash.features.extractors.FeatureExtractor.to_dict

    """
    assert "feature_extractors" in fe_dict
    kwargs = {}
    if "preprocessor" in fe_dict:
        kwargs["preprocessor"] = _func_from_dict(fe_dict["preprocessor"])
    fes = {}
    for k, v in fe_dict["feature_extractors"].items():
        assert isinstance(v, dict)
        if "feature_extractors" in v:
            fes[k] = feature_extractor_from_dict(v)
        elif "name" in v:
            fes[k] = _func_from_dict(v)
        else:
            raise ValueError(
                f"Feature {k}: A feature dict must "
                + "contain either a 'feature_extractors' "
                + "field (for `FeatureExtractor`)or a 'name' "
                + f"field (for a function), got {v.keys()}."
            )
    kwargs["feature_extractors"] = fes
    return FeatureExtractor(**kwargs)


def load_feature_extractor_from_json(path: str | Path) -> FeatureExtractor:
    """Reads a feature extractor from a json file.

    Parameters
    ----------
    path : str | pathlib.Path
        The path to the json file.

    See Also
    --------
    ~eegdash.features.extractors.FeatureExtractor.to_json

    """
    import json

    # Verify work with a pathlib.Path
    path = Path(path)

    with open(path, "r") as file:
        fe_dict = json.load(file)

    return feature_extractor_from_dict(fe_dict)


def load_feature_extractor_from_yaml(path: str | Path) -> FeatureExtractor:
    """Reads a feature extractor from a yaml file.

    Parameters
    ----------
    path : str | pathlib.Path
        The path to the yaml file.

    Notes
    -----
    Requires the `yaml` package.

    See Also
    --------
    ~eegdash.features.extractors.FeatureExtractor.to_yaml

    """
    import yaml

    # Verify work with a pathlib.Path
    path = Path(path)

    with open(path, "r") as file:
        fe_dict = yaml.safe_load(file)

    return feature_extractor_from_dict(fe_dict)


def load_feature_extractor_from_hocon(path: str | Path) -> FeatureExtractor:
    """Reads a feature extractor from a HOCON's conf file.

    Parameters
    ----------
    path : str | pathlib.Path
        The path to the conf file.

    See Also
    --------
    ~eegdash.features.extractors.FeatureExtractor.to_hocon

    Notes
    -----
    Requires the `pyhocon` package.

    """
    from pyhocon import ConfigFactory

    # Verify work with a pathlib.Path
    path = Path(path)

    fe_dict = ConfigFactory.parse_file(path)

    return feature_extractor_from_dict(fe_dict)
