#!/usr/bin/env python3
"""Generate ``source/_static/dataset_generated/traces-viewer-recordings.json``.

Maps dataset_id → one representative recording so the eegdash-viewer
iframe (https://eegdash.github.io/eegdash-viewer/) can build a
sensible default ``?dataset=&sub=&task=…&ext=`` URL per dataset
page. Mirror of build_electrode_layouts.py for the trace-viewer
embed; lives next to it for parity.

Initial implementation: hand-curated subset of datasets that have
been validated end-to-end against the live viewer + CDN. Future
work: query the eegdash backend's recording index to produce a
representative recording per indexed dataset, mirroring the way
build_electrode_layouts.py queries the montage registry.

Usage::

    python build_traces_recordings.py

The output file is gitignored (see .gitignore: dataset_generated/).
Sphinx's ``conf._format_traces_section`` reads this file at doc-build
time; missing manifest degrades silently to no Signal Preview block.
"""

from __future__ import annotations

import datetime as _dt
import json
from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parent
OUTPUT = (
    DOCS_DIR
    / "source"
    / "_static"
    / "dataset_generated"
    / "traces-viewer-recordings.json"
)

VIEWER_BASE = "https://eegdash.github.io/eegdash-viewer/"

# Hand-curated initial OpenNeuro set: three formats × three datasets,
# each validated end-to-end via tests/e2e/multi-record-smoke.spec.mjs
# in the eegdash-viewer repo (real Chromium loads each through the
# Cloudflare Worker proxy; canvas paints, no console errors).
OPENNEURO_RECORDINGS: dict[str, dict[str, object]] = {
    "ds002893": {
        "label": "EEGLAB · 36 channels · 250 Hz",
        "sub": "001",
        "task": "AuditoryVisualShift",
        "run": "01",
        "ext": "set",
        "n_channels": 36,
        "fs_hz": 250,
    },
    "ds002034": {
        "label": "EDF · 82 channels · 512 Hz",
        "sub": "01",
        "ses": "01",
        "task": "offline",
        "run": "01",
        "ext": "edf",
        "n_channels": 82,
        "fs_hz": 512,
    },
    "ds002336": {
        "label": "BrainVision · 64 channels · 5000 Hz",
        "sub": "xp101",
        "task": "motorloc",
        "ext": "vhdr",
        "n_channels": 64,
        "fs_hz": 5000,
    },
}

# NEMAR-only set: nm-prefixed datasets resolve via the eegdash
# records API (one call returns sidecars inline plus the SHA-keyed
# binary URL), then route the binary through cdn.eegdash.org which
# proxies nemar.s3.amazonaws.com and adds the missing CORS layer.
# Curated separately from OpenNeuro because the resolution path,
# upstream constraints, and validation suite all differ.
#
# Inline-data .set is the common modern EEGLAB layout (single .set
# file with the data array inside the MAT struct, no sibling .fdt);
# the viewer's reader downloads + parses the MAT v5 in the worker.
# Other NEMAR formats are blocked upstream today: BrainVision
# (nm000166) and EDF (nm000181) datasets return S3 403 on their
# annex objects (NEMAR-side ACL gap).
NEMAR_RECORDINGS: dict[str, dict[str, object]] = {
    # nm000121: smallest NEMAR .set (~1 MB, 14 ch, 128 Hz, ~140 s),
    # inline-data MAT v5. Snappiest demo of the SHA-keyed S3 path
    # plus the inline-MAT parser path in the same recording.
    "nm000121": {
        "label": "NEMAR EEGLAB · 14 channels · 128 Hz · SSVEP",
        "sub": "6",
        "ses": "0",
        "task": "ssvep",
        "run": "6",
        "ext": "set",
        "n_channels": 14,
        "fs_hz": 128,
    },
}

RECORDINGS: dict[str, dict[str, object]] = {
    **OPENNEURO_RECORDINGS,
    **NEMAR_RECORDINGS,
}


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    doc = {
        "_comment": (
            "Auto-generated by docs/build_traces_recordings.py. Maps dataset_id → "
            "representative recording for the eegdash-viewer iframe. Do not edit by hand."
        ),
        "_schema_version": 1,
        "_generated_at": _dt.datetime.now(_dt.timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z"),
        "_viewer_base": VIEWER_BASE,
        "recordings": RECORDINGS,
    }
    OUTPUT.write_text(
        json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"Wrote {OUTPUT.relative_to(DOCS_DIR)} ({len(RECORDINGS)} recordings)")


if __name__ == "__main__":
    main()
